const statesAndCities = {
    Alabama: ['Birmingham', 'Montgomery', 'Mobile'],
    Alaska: ['Anchorage', 'Fairbanks', 'Juneau'],
    Arizona: ['Phoenix', 'Tucson', 'Mesa'],
    Arkansas: ['Little Rock', 'Fort Smith', 'Fayetteville'],
    California: ['Los Angeles', 'San Diego', 'San Jose'],
    Colorado: ['Denver', 'Colorado Springs', 'Aurora'],
    Connecticut: ['Bridgeport', 'New Haven', 'Hartford'],
    Delaware: ['Wilmington', 'Dover', 'Newark'],
    Florida: ['Jacksonville', 'Miami', 'Tampa'],
    Georgia: ['Atlanta', 'Augusta', 'Columbus'],
    Hawaii: ['Honolulu', 'Pearl City', 'Hilo'],
    Idaho: ['Boise', 'Nampa', 'Meridian'],
    Illinois: ['Chicago', 'Aurora', 'Rockford'],
    Indiana: ['Indianapolis', 'Fort Wayne', 'Evansville'],
    Iowa: ['Des Moines', 'Cedar Rapids', 'Davenport'],
    Kansas: ['Wichita', 'Overland Park', 'Kansas City'],
    Kentucky: ['Louisville', 'Lexington', 'Bowling Green'],
    Louisiana: ['New Orleans', 'Baton Rouge', 'Shreveport'],
    Maine: ['Portland', 'Lewiston', 'Bangor'],
    Maryland: ['Baltimore', 'Frederick', 'Rockville'],
    Massachusetts: ['Boston', 'Worcester', 'Springfield'],
    Michigan: ['Detroit', 'Grand Rapids', 'Warren'],
    Minnesota: ['Minneapolis', 'Saint Paul', 'Rochester'],
    Mississippi: ['Jackson', 'Gulfport', 'Southaven'],
    Missouri: ['Kansas City', 'Saint Louis', 'Springfield'],
    Montana: ['Billings', 'Missoula', 'Great Falls'],
    Nebraska: ['Omaha', 'Lincoln', 'Bellevue'],
    Nevada: ['Las Vegas', 'Henderson', 'Reno'],
    NewHampshire: ['Manchester', 'Nashua', 'Concord'],
    NewJersey: ['Newark', 'Jersey City', 'Paterson'],
    NewMexico: ['Albuquerque', 'Las Cruces', 'Rio Rancho'],
    NewYork: ['New York', 'Buffalo', 'Rochester'],
    NorthCarolina: ['Charlotte', 'Raleigh', 'Greensboro'],
    NorthDakota: ['Fargo', 'Bismarck', 'Grand Forks'],
    Ohio: ['Columbus', 'Cleveland', 'Cincinnati'],
    Oklahoma: ['Oklahoma City', 'Tulsa', 'Norman'],
    Oregon: ['Portland', 'Salem', 'Eugene'],
    Pennsylvania: ['Philadelphia', 'Pittsburgh', 'Allentown'],
    RhodeIsland: ['Providence', 'Warwick', 'Cranston'],
    SouthCarolina: ['Columbia', 'Charleston', 'North Charleston'],
    SouthDakota: ['Sioux Falls', 'Rapid City', 'Aberdeen'],
    Tennessee: ['Nashville', 'Memphis', 'Knoxville'],
    Texas: ['Houston', 'San Antonio', 'Dallas'],
    Utah: ['Salt Lake City', 'West Valley City', 'Provo'],
    Vermont: ['Burlington', 'Essex', 'South Burlington'],
    Virginia: ['Virginia Beach', 'Norfolk', 'Chesapeake'],
    Washington: ['Seattle', 'Spokane', 'Tacoma'],
    WestVirginia: ['Charleston', 'Huntington', 'Morgantown'],
    Wisconsin: ['Milwaukee', 'Madison', 'Green Bay'],
    Wyoming: ['Cheyenne', 'Casper', 'Laramie'],
  };
  
  export default statesAndCities;